Repository SebastianBoe/fw-nrfconnect-nrf-1, pull requests merged in 2022-01, with the labels that each got.

#3 applications: asset_tracker: fix LOG argument type
  applications/asset_tracker/src/main.c
Labels: changelog-entry-required, CI-thingy91-test

#6 tests/modules/mcuboot.external_flash: fix MCUboot size issue
  tests/modules/mcuboot/external_flash/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.conf
Labels: changelog-entry-required

#4 applications: serial_lte_modem: Fix build with native TLS
  applications/serial_lte_modem/overlay-native_tls.conf
Labels: changelog-entry-required

#8 subsystem: openthread: adjust mbedtls configuration to nRF Security
  subsys/net/openthread/Kconfig.defconfig
Labels: CI-matter-test, changelog-entry-required, CI-thread-test

#11 app: serial_lte_modem: Update native tls mbedtls config
  applications/serial_lte_modem/overlay-native_tls.conf
Labels: changelog-entry-required

#12 samples: openthread: add entropy hardware poll fix for TF-M builds
  samples/openthread/cli/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
  samples/openthread/cli/prj.conf
  samples/openthread/coap_client/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
  samples/openthread/coap_server/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
Labels: changelog-entry-required, CI-thread-test
